### ISSUE TITLE
Graph arc

### ISSUE THREAD

**Issue by lapnd** [mwang005/a-deep-dive-into-vpp#1]
Hi mwang005,
How did you generate the graph arc? 
for example in the file A_Deep_Dive_into_VPP(01)-Runtime_Dispatching_Node_graph.pdf
(The node graph for ping was generated)
Thank you!

**Comment by mwang005** [comment]
Hi Lap，

 

Normally, there is a way to generate it manually as following steps

1)      Capture trace

# trace add dpdk-input 100

To ping VPP from host or send packets to VPP from traffic generator 

# show trace

2)      the trace will show packet dispatched from the previous node to next.

Note that each node can dispatch packet to the different next nodes. 

You can find the next nodes by source code, e.g.

VLIB_REGISTER_NODE(dpdk_input_node) = {

…

.name = "dpdk-input",

…

.n_next_nodes= DPDK_RX_N_NEXT,

.next_nodes= {

[DPDK_RX_NEXT_DROP] = "error-drop",

[DPDK_RX_NEXT_ETHERNET_INPUT] = "ethernet-input",

[DPDK_RX_NEXT_IP4_INPUT] = "ip4-input-no-checksum",

[DPDK_RX_NEXT_IP6_INPUT] = "ip6-input",

[DPDK_RX_NEXT_MPLS_INPUT] = "mpls-gre-input",

},

};

 

Or by the CLI

# show vlib graph

           Name                      Next                    Previous         

TenGigabitEthernet86/0/0-o      error-drop [0]               ip4-glean        

                          TenGigabitEthernet86/0/0-t     interface-output     

 

TenGigabitEthernet86/0/0-t      error-drop [0]      TenGigabitEthernet86/0/0-o

 

TenGigabitEthernet86/0/1-o      error-drop [0]               ip4-glean        

                          TenGigabitEthernet86/0/1-t     interface-output     

<etc>

 

3)      to collect all nodes were traced and connect the nodes with arcs

 

HTH

 

Thanks,

Michael

 

From: bounces+848413-b57a-wangmeng=certusnet.com.cn@sgmail.github.com [mailto:bounces+848413-b57a-wangmeng=certusnet.com.cn@sgmail.github.com] On Behalf Of Lap Ngo
Sent: Wednesday, September 13, 2017 12:38 PM
To: mwang005/a-deep-dive-into-vpp <a-deep-dive-into-vpp@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: [mwang005/a-deep-dive-into-vpp] Graph arc (#1)

 

Hi mwang005,
How did you generate the graph arc?
for example in the file A_Deep_Dive_into_VPP(01)-Runtime_Dispatching_Node_graph.pdf
(The node graph for ping was generated)
Thank you!

**Comment by lapnd** [comment]
Thank you very much, Michael!
You did a great job to help people understand VPP!
